[package]
name = "lang-apis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.8.0"
env_logger = "0.11.3"
serde = "1.0.204"




[build-dependencies]
tonic-build = "0.10.2"
